import { Router } from 'express';
import { authRouter } from '../modules/auth/auth.routes.js';
import { healthRouter } from '../modules/health/health.routes.js';
import { articuloRouter } from '../modules/articulos/articulo.routes.js';
import { opcionMenuRouter } from '../modules/opciones-menu/opcion-menu.routes.js';
import { clienteRouter } from '../modules/clientes/cliente.routes.js';
import { proveedorRouter } from '../modules/proveedores/proveedor.routes.js';
import { compraRouter } from '../modules/compras/compra.routes.js';
import { taxRateRouter } from '../modules/tax-rates/tax-rate.routes.js';
import { eventoRouter } from '../modules/eventos/evento.routes.js';
import { inventarioRouter } from '../modules/inventario/inventario.routes.js';
import { dashboardRouter } from '../modules/dashboard/dashboard.routes.js';
import { gastoAdministrativoRouter } from '../modules/gastos-administrativos/gasto-administrativo.routes.js';
import { juegoInventariosRouter } from '../modules/juego-inventarios/juego-inventarios.routes.js';
import { estadoResultadosRouter } from '../modules/estado-resultados/estado-resultados.routes.js';
import { nominaRouter } from '../modules/nomina/nomina.routes.js';
import { negocioRouter } from '../modules/crm/negocio.routes.js';
import { agendaRouter } from '../modules/agenda/agenda.routes.js';
import { carteraRouter } from '../modules/cartera/cartera.routes.js';
import { userRouter } from '../modules/usuarios/user.routes.js';
import { cotizacionRouter } from '../modules/cotizaciones/cotizacion.routes.js';
import { auditoriaRouter } from '../modules/auditoria/auditoria.routes.js';
import { notificacionRouter } from '../modules/notificaciones/notificacion.routes.js';

export const router = Router();

router.use('/health', healthRouter);
router.use('/auth', authRouter);
router.use('/articulos', articuloRouter);
router.use('/opciones-menu', opcionMenuRouter);
router.use('/clientes', clienteRouter);
router.use('/proveedores', proveedorRouter);
router.use('/compras', compraRouter);
router.use('/tax-rates', taxRateRouter);
router.use('/eventos', eventoRouter);
router.use('/inventario', inventarioRouter);
router.use('/dashboard', dashboardRouter);
router.use('/gastos-administrativos', gastoAdministrativoRouter);
router.use('/juego-inventarios', juegoInventariosRouter);
router.use('/estado-resultados', estadoResultadosRouter);
router.use('/nomina', nominaRouter);
router.use('/negocios', negocioRouter);
router.use('/agenda', agendaRouter);
router.use('/cartera', carteraRouter);
router.use('/usuarios', userRouter);
router.use('/cotizaciones', cotizacionRouter);
router.use('/auditoria', auditoriaRouter);
router.use('/notificaciones', notificacionRouter);
